---
deploy__healthcheck_systemd_service: |
  [Unit]
  Description=healtheck for application

  [Service]
  Restart=always
  User=root
  ExecStart={{ deploy__app_dir }}/healthcheck.sh
  ExecStop=/bin/kill -HUP $MAINPID
  StartLimitBurst=30
  RestartSec=5
  StartLimitInterval=200
  SendSIGKILL=no

  [Install]
  WantedBy=multi-user.target
  WantedBy=bingo.service
